linters:
  enable-all: true

  disable:
    - errchkjson # Because it panics with: "fatal error: stack overflow" XXX Revisit
    - goerr113
    - gofumpt    # Prefer `gofmt` rules / some rules conflict with `wsl`
    - gomnd      # XXX: For now
    # The following are deprecated linters, added to avoid intial warning when running
    - golint
    - interfacer
    - maligned
    - scopelint

linters-settings:
  lll:
    line-length: 130
  gci:
    no-inline-comments: true
    no-prefix-comments: true
    sections:
      - standard
      - default
      - prefix(github.com/MarioCarrion/todo-api)
    section-separators:
      - newLine
  exhaustivestruct:
    struct-patterns:
      - 'github.com/MarioCarrion/todo-api/internal.*Params'
  ireturn:
    allow:
      - error
      - stdlib
      #
      - 'go.opentelemetry.io/otel/trace.Span'
  varnamelen:
    max-distance: 10
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-decls:
      - b bytes.Buffer
      - h http.Handler
      - id string
      - ok bool
      - r *http.Request
      - w http.ResponseWriter
  wrapcheck:
    ignoreSigs:
      - internaldomain.WrapErrorf(
      - internaldomain.NewErrorf(
      - internal.NewErrorf(
      - internal.WrapErrorf(
    ignorePackageGlobs:
      - github.com/MarioCarrion/todo-api/* 
issues:
  exclude-rules:
    # All tests
    - path: _test\.go
      linters:
        - cyclop
        - errchkjson
        - exhaustivestruct
        - funlen
        - goerr113
        - lll
        - varnamelen
        - wrapcheck
    # Handles the C4 diagrams
    - path: internal/doc/doc.go
      linters:
        - lll
        - revive
        - stylecheck
    # Generates OpenAPI 3 documentation
    - path: internal/rest/open_api.go
      linters:
        - funlen
    # Final binaries
    - path: cmd/
      linters:
        - cyclop
        - funlen
        - gocognit
        - unparam
    # Handles generating code from OpenAPI 3
    - path: cmd/openapi-gen/main.go
      linters:
        - forbidigo
    - path: cmd/internal/postgresql.go
      linters:
        - revive # blank-imports
    # XXX: This will be reremove in future episodes when "exhaustivestruct" is enabled
    - path: internal/postgresql/task.go
      linters:
        - lll
    - path: internal/memcached/task.go
      linters:
        - lll
    # Because of the env var testing and using t.Setenv
    - path: internal/envvar/envvar_test.go
      linters:
        - paralleltest
        - thelper
        - tparallel
