name: Lint

on: push

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.1-0.20211114223346-ec58c4818038
          args: --timeout=3m
